version: 1
story:
    title: ""
    author: Your Name Here
    genre: drama
    cover: ""
    finished: false
settings:
    using_template: false
    templates: # custom template, should be in template/
        index:
        chapter:
        style:
    format: markdown # prefered format for new chapter, no use for now
chapters: []
